### ISSUE TITLE
Torrent and ytdl download is not working.

### ISSUE THREAD

**Issue by hackevil** [MaxxRider/Maxx-Mirror-Pro#15]
I deployed your repo yesterday on heroku and everything went smooth and the bot got deployed successfully but when i tried to download some torrents, it was not working and got stuck and after sometime it stopped the download stating due to less seed(torrent had 600+ seed)

btw normal http link files were downloading and uploading successfully it was just not working for torrent and ytdl.
i have attached the log files and a screenshot

` [https://del.dog/ydagawesat.txt](url) 

screenshot [https://telegra.ph/Screenshot-01-09-29](url)

**Comment by MaxxRider** [comment]
ok tomorrow I'll check
